version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/script.sql
